# Generated by Django 5.0.4 on 2024-04-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название должности')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество сотрудника')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона сотрудника')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта сотрудника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.position')),
            ],
        ),
    ]
