# Generated by Django 5.0.4 on 2024-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='TaskStatus',
        ),
    ]
