# Generated by Django 5.0.4 on 2024-06-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0004_rename_task_tasks_rename_status_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='TaskManagerApp.employee', verbose_name='Назначил'),
        ),
    ]
